version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: sword123
      MYSQL_DATABASE: sword
      MYSQL_USER: sword_root
      MYSQL_PASSWORD: sword123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sword_network
    restart: always

  rmq:
    image: rabbitmq:management
    container_name: rmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - sword_network
    restart: always

volumes:
  mysql_data:
    driver: local

networks:
  sword_network:
    driver: bridge
