import { IsNotEmpty, IsNumber, IsOptional } from 'class-validator';
import { TaskBaseDto } from './task-base.dto';
import { ApiProperty } from '@nestjs/swagger';

export class TaskCreateDto extends TaskBaseDto {
  @ApiProperty({
    description:
      'Unique identifier for the user. This ID is automatically generated by the system and is used to uniquely reference a user.',
    example: 1,
  })
  @IsNumber()
  @IsNotEmpty()
  public userId: number;
}
export class TaskCreateRequestDto extends TaskBaseDto {
  @ApiProperty({
    description:
      'Unique identifier for the user. This ID is optional. If not provided, the userId of the currently logged-in user will be used by default.',
    example: 1,
  })
  @IsNumber()
  @IsOptional()
  public userId?: number;
}
