import { ApiProperty } from '@nestjs/swagger';
import { IsEnum, IsNumber, IsOptional } from 'class-validator';
import { TaskStatusEnum } from './task-base.dto';

export class TaskFilterDto {
  @ApiProperty({
    description:
      'Unique identifier for the user. This ID is automatically generated by the system and is used to uniquely reference a user',
    example: 123,
  })
  @IsNumber()
  @IsOptional()
  public userId?: number;

  @ApiProperty({
    description: 'Current status of the task.',
    example: TaskStatusEnum.IN_PROGRESS,
    enum: TaskStatusEnum,
  })
  @IsEnum(TaskStatusEnum)
  @IsOptional()
  public status?: TaskStatusEnum;
}
