import { IsNotEmpty, IsNumber } from 'class-validator';
import { UserBaseDto } from './user-base.dto';
import { ApiProperty } from '@nestjs/swagger';

export class UserDto extends UserBaseDto {
  @ApiProperty({
    description:
      'Unique identifier for the user. This ID is automatically generated by the system and is used to uniquely reference a user.',
    example: 1,
  })
  @IsNumber()
  @IsNotEmpty()
  public userId: number;
}
